Fixed 'Cannot use type Post as an array'
Error: "Fatal error:  Cannot use object of type
Automattic\Syndication\Types\Post as array" was being caused because
$post was being used instead of $post->post_data